services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: habits_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres_habits
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    networks:
      - haru-network

  db:
    image: postgres:16-alpine
    container_name: postgres_habits
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres_habits
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - haru-network

volumes:
  postgres_data:

networks:
  haru-network:
    driver: bridge
