spring:
  datasource:
    url: jdbc:postgresql://172.27.0.2:5432/postgres_habits
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  docker:
    compose:
      file: backend/docker-compose.yaml
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: docker

server:
  port: 8080

logging:
  level:
    root: info
    org:
      springframework: debug